service:
  gocloudAPI:
    name: gocloud-api
    replicaCount: 1
    labels:
      app: gocloud
      tier: frontend
      component: web
    image:
      repository: marktward/gocloud
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      containerPort:
        port: 8010
        name: gocloud-fe
    command: "[\"gocloud\", \"restapi\", \"start\"]"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  gocloudGrpc:
    name: gocloud-grpc
    replicaCount: 1
    labels:
      app: gocloud
      tier: backend
      component: grpc
    image:
      repository: marktward/gocloud
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      containerPort:
        port: 8000
        name: gocloud-be
    command: "[\"gocloud\", \"grpc\", \"serve\"]"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
