service:
  gocloudAPI:
    name: gocloud-api
    replicaCount: 1
    labels:
      app: gocloud
      tier: frontend
      component: api
    image:
      repository: gcr.io/k8sdemo-159622/gocloud
      tag: latest
      pullPolicy: Always
    serviceType: LoadBalancer
    serviceName: gocloud-api
    servicePort: 8010
    ports:
      name: gocloud-fe
      containerPort: 8010
      targetPort: 8010
      protocol: TCP
    command: "[\"gocloud\", \"restapi\", \"start\"]"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  gocloudGrpc:
    name: gocloud-grpc
    replicaCount: 1
    labels:
      app: gocloud
      tier: backend
      component: grpc
    image:
      repository: gcr.io/k8sdemo-159622/gocloud
      tag: latest
      pullPolicy: Always
    serviceName: gocloud-grpc
    servicePort: 8000
    ports:
      name: gocloud-be
      containerPort: 8000
      targetPort: 8000
      protocol: TCP
    command: "[\"gocloud\", \"grpc\", \"serve\"]"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
