apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.service.gocloudAPI.name }}"
  # name: {{ template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{ .Values.service.gocloudAPI.labels.component }}"
spec:
  replicas: {{ .Values.service.gocloudAPI.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.gocloudAPI.labels.app }}
        tier: {{ .Values.service.gocloudAPI.labels.tier }}
        component: {{ .Values.service.gocloudAPI.labels.component }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: gocloud-fe
        image: "{{ .Values.service.gocloudAPI.image.repository}}:{{.Values.service.gocloudAPI.image.tag }}"
        imagePullPolicy: "{{ .Values.service.gocloudAPI.image.pullPolicy}}"
        ports:
        - containerPort: {{ .Values.service.gocloudAPI.ports.containerPort.port }}
          name: {{ .Values.service.gocloudAPI.ports.containerPort.name }}
        command: {{ .Values.service.gocloudAPI.command }}
