language: go
sudo: required
go:
- 1.8.x
env:
- HELM_VERSION: v2.3.1
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
- pwd
- GOCLOUD_CICD_DIR="external/github.com/marktward/gocloud-cicd"
- mkdir -p $GOCLOUD_CICD_DIR
- git clone https://github.com/markTward/gocloud-cicd.git $GOCLOUD_CICD_DIR
- wget "https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz"
- tar -xzf "helm-${HELM_VERSION}-linux-amd64.tar.gz"
- sudo mv linux-amd64/helm /usr/local/bin/helm && ls -la /usr/local/bin/helm
- helm help
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud version
- openssl aes-256-cbc -K $encrypted_2a9422d072d6_key -iv $encrypted_2a9422d072d6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz.enc; ls -la
install:
- go get -d -v ./...
- go get -d -v github.com/stretchr/testify/assert
script:
- env | grep -v DOCKER | sort
- go test -v ./...
- export DOCKER_REPO=$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')
- export DOCKER_COMMIT_TAG=${TRAVIS_COMMIT::7}
- docker build -t $DOCKER_REPO:$DOCKER_COMMIT_TAG -f Dockerfile .
after_success:
- "./$GOCLOUD_CICD_DIR/travis/docker_push.sh"
- helm lint deploy/helm/gocloud/
notifications:
  email: false
  slack:
    secure: ifhkq27en11fNB4zTw5MRjn4ef+3C9NbysrH5pIVejjfQSYeqw2eIfrD/XbKiEUBlLd9LKg4FkhoHnkr9CHO2H+JkZYJWy5fuH4qPJX/m5YN92ZCuIpocFUOsr9+q1NrMDUlmVrLzTA7MTIn1RVCggDQMwL7gdkQDnTz9ROvCWQnKFYlo2PRB7E/PhSNgsBn6FvpXJLNjv640eaNI9h82n4IMzJWEjMyUJNGXxRL1gvyUGrFJ+7DavJVTbnN1zq1SBZRTgVsvCHWGR3fMjFa3Nw9YQpThR6W8LYCXclSOX+RnKmeThxaKuYjm3up2jBJFWdqxswqWQQl0J/HLuD2KGfvz3D0hgKy7ytIhOtKzJAJklR4N/GSqjYvK80CfYBdddhxAsjMp/nB0Fud5zeM6gCPzp9YxK/KLo9C3UyGV7BCci915y49g8+9gicBYlHULdD5KG4VlsFRyuVGXEI6Z7nkA6JOAaiNsWjLcPFKF9CjAn0idfrvx//sBxoSz36WDZOTxD7tWHAE0fdxvJsMOzSdEgdl/8uIDoukdw5UrG4j2UsF/wWfUf8harerktWpaYj69PzDjdc1Pn6xOziunlEzeYLC44uElSvFfAPi/ABYNk8J3SxVEXVyh/lfvqzbJfk1cQk0aT4z/j2Lq1Z50p89k/fQq1louOkAqLPxcxI=
