language: go
sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=marktward/gocloud

go:
  - 1.8.x

services:
  - docker

install:
  - go get -d -v ./...
  - go get -d -v github.com/stretchr/testify/assert

script:
  - env | sort
  - go test -v ./...
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TAG -f Dockerfile .

after_success:
 # - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
   - docker tag $REPO:$COMMIT $REPO:$TAG
   - docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
   - docker images
 # - docker push $REPO

notifications:
  email: false
