language: go
sudo: required
go:
- 1.8.x
env:
  global:
  - GOCLOUD_CICD_CONFIG_FILE=./cicd.yaml
  - DOCKER_COMMIT_TAG=${TRAVIS_COMMIT::7}
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
services:
- docker
before_install:
# python yaml required for parsing cicd.yaml into json
- pip install pyyaml
- sudo apt-get update
- sudo apt-get install -y jq
install:
# bootstrap gocloud-cicd clone arguments from cicd.yaml
# clone CICD tools, get dependencies and build binaries
- GOCLOUD_CICD_CONFIG_FILE=./cicd.yaml
- GOCLOUD_CICD_JSON=$(python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < ./cicd.yaml)
- GOCLOUD_APP_NAME=$(echo $GOCLOUD_CICD_JSON | jq -r .app.name)
- GOCLOUD_CICD_REPO=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.github.repo)
- GOCLOUD_CICD_BRANCH=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.github.branch)
- GOCLOUD_CICD_DIR=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.github.clonedir)
- mkdir -p $GOCLOUD_CICD_DIR
- git clone -b $GOCLOUD_CICD_BRANCH $GOCLOUD_CICD_REPO $GOCLOUD_CICD_DIR
- go get -d -v $GOCLOUD_CICD_DIR/...
- go build -o $GOPATH/bin/docker_push $GOCLOUD_CICD_DIR/travis/docker_push/
# get project dependencies
- go get -d -v ./...
- go get -d -v github.com/stretchr/testify/assert
# install helm
- GOCLOUD_HELM_VERSION=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.cdprovider.helm.version)
- wget "https://storage.googleapis.com/kubernetes-helm/helm-${GOCLOUD_HELM_VERSION}-linux-amd64.tar.gz"
- tar -xzf "helm-${GOCLOUD_HELM_VERSION}-linux-amd64.tar.gz"
- sudo mv linux-amd64/helm /usr/local/bin/helm
- helm version --client
# install gcloud && kubectl
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- sudo gcloud --quiet components install kubectl
- sudo gcloud --quiet components update
- sudo ln -s /usr/lib/google-cloud-sdk/bin/kubectl /usr/local/bin/kubectl
- which gcloud || true
- which kubectl || true
- gcloud version
- kubectl version --client=true || true
before_script:
# gcloud service account credentials
- openssl aes-256-cbc -K $encrypted_2a9422d072d6_key -iv $encrypted_2a9422d072d6_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
- sudo gcloud auth activate-service-account --key-file client-secret.json
- sudo gcloud auth list
# gcloud configurations
- GOCLOUD_GKE_CLUSTER=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.platform.gke.cluster)
- GOCLOUD_GKE_COMPUTE_ZONE=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.platform.gke.computezone)
- GOCLOUD_GKE_PROJECT=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.platform.gke.project)
- sudo gcloud config set project $GOCLOUD_GKE_PROJECT
- sudo gcloud config set container/cluster $GOCLOUD_GKE_CLUSTER
- sudo gcloud config set compute/zone ${GOCLOUD_GKE_COMPUTE_ZONE}
- sudo gcloud config list
- sudo gcloud container clusters get-credentials $GOCLOUD_GKE_CLUSTER
script:
- go test -v ./...
- docker build -t $GOCLOUD_APP_NAME:$DOCKER_COMMIT_TAG -f Dockerfile .
after_success:
- "sudo $GOPATH/bin/docker_push --image $GOCLOUD_APP_NAME:$DOCKER_COMMIT_TAG --branch $TRAVIS_BRANCH --config $GOCLOUD_CICD_CONFIG_FILE --event $TRAVIS_EVENT_TYPE --tag $DOCKER_COMMIT_TAG --pr $TRAVIS_PULL_REQUEST"
before_deploy:
# show k8s context
- sudo kubectl config get-contexts
# helm / k8s state before deploy
# BUG: helm fails to obtain k8s cluster access token; must run kubectl command first
- sudo kubectl get namespaces
- sudo helm lint --strict --debug helm/gocloud/
- sudo helm list
- GOCLOUD_HELM_NAMESPACE=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.cdprovider.helm.namespace)
- GOCLOUD_HELM_CHARTPATH=$(echo $GOCLOUD_CICD_JSON | jq -r .workflow.cdprovider.helm.chartpath)
- DOCKER_REPO=gcr.io/$GOCLOUD_GKE_PROJECT/$GOCLOUD_APP_NAME
deploy:
  - provider: script
    on:
      all_branches: true
    # TODO: integrate with forthcoming go-based deployment script; derived from cicd.yaml
    script: sudo $GOCLOUD_CICD_DIR/travis/deploy_k8s.sh $DOCKER_REPO $DOCKER_COMMIT_TAG $GOCLOUD_APP_NAME-$TRAVIS_BRANCH LIVE $GOCLOUD_HELM_NAMESPACE $GOCLOUD_HELM_CHARTPATH
after_deploy:
- sudo kubectl get svc,deploy,pod --namespace=$GOCLOUD_HELM_NAMESPACE
- sudo helm list
notifications:
  email: false
  slack:
    secure: ifhkq27en11fNB4zTw5MRjn4ef+3C9NbysrH5pIVejjfQSYeqw2eIfrD/XbKiEUBlLd9LKg4FkhoHnkr9CHO2H+JkZYJWy5fuH4qPJX/m5YN92ZCuIpocFUOsr9+q1NrMDUlmVrLzTA7MTIn1RVCggDQMwL7gdkQDnTz9ROvCWQnKFYlo2PRB7E/PhSNgsBn6FvpXJLNjv640eaNI9h82n4IMzJWEjMyUJNGXxRL1gvyUGrFJ+7DavJVTbnN1zq1SBZRTgVsvCHWGR3fMjFa3Nw9YQpThR6W8LYCXclSOX+RnKmeThxaKuYjm3up2jBJFWdqxswqWQQl0J/HLuD2KGfvz3D0hgKy7ytIhOtKzJAJklR4N/GSqjYvK80CfYBdddhxAsjMp/nB0Fud5zeM6gCPzp9YxK/KLo9C3UyGV7BCci915y49g8+9gicBYlHULdD5KG4VlsFRyuVGXEI6Z7nkA6JOAaiNsWjLcPFKF9CjAn0idfrvx//sBxoSz36WDZOTxD7tWHAE0fdxvJsMOzSdEgdl/8uIDoukdw5UrG4j2UsF/wWfUf8harerktWpaYj69PzDjdc1Pn6xOziunlEzeYLC44uElSvFfAPi/ABYNk8J3SxVEXVyh/lfvqzbJfk1cQk0aT4z/j2Lq1Z50p89k/fQq1louOkAqLPxcxI=
