language: go
sudo: required
go:
- 1.8.x
env:
  matrix:
    secure: V1AFPrV83iQ2TN5x1HaNfj7FM/3R8ijld+3Ogj9xlfZ3fBqvMXS4wdbFGRENhi+MqTuX6DH1tunTmcxzNWNJonaNmlxWg26PpOWLGTFd2MEsy4+IijOVrLrcL3oPJnwS9+mPqMqdrVBZGpej6ZwoTu6rhVLDE6Pm8olaXb3ZDIXpovJjqoVajd73/MKr2dyHUEzu+lbOdCFfnLCtkMp5WMGasrqz1tlCNniQ4AUiXUQ+r3ibTEiYlhPuETcotJgpTMQ2xfDlYLWK1LaglIGV/TwoWeLxk8BH4icRBLGxIcU/Kb5iasECocD7SFt8bykXRN2HnuxSg5Md8HzoFoT2Igd+3pBM4EUCDYb0nwNgXURohVPTxOv7crbqLMJ/9AfopK08UwNF418fQnPZlDS4LhZkUs5DeNTQqYc89xaAsnnXRbcG3IXTAZgfDc9RQcbEgcAVeiZQUt8jpKP20ZfUlNTLzmrFkCPsPJvSh/MTt9hktqFsY1vF2/jM+9qUD3HwCVmCrP4syU25Zk3MGLSmXktJd0WNUeDQ8m/bPhp23EVOkyp3snN00I4e6vomYqoAbTShg4iwzO8b/2rYuo7uZYEd4ittlPBcNwZqerRgEEoDL4PTCOvJdBMG6ZeSwxcsbWTWIIHIrOXAv32EIg7aIOwuShqpalYmyUWSCqxl33g=
services:
- docker
before_install:
- pwd
- mkdir -p external/github.com
- git clone https://github.com/markTward/gocloud-cicd.git external/github.com/gocloud-cicd
- ls -la external/github.com/gocloud-cicd; cat external/github.com/gocloud-cicd/README.md
install:
- go get -d -v ./...
- go get -d -v github.com/stretchr/testify/assert
script:
- env | sort
- go test -v ./...
- export DOCKER_REPO=$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')
- docker build -t $DOCKER_REPO:$TRAVIS_COMMIT -f Dockerfile .
after_success:
- "./deploy/docker_push.sh"
notifications:
  email: false
  slack:
    secure: ifhkq27en11fNB4zTw5MRjn4ef+3C9NbysrH5pIVejjfQSYeqw2eIfrD/XbKiEUBlLd9LKg4FkhoHnkr9CHO2H+JkZYJWy5fuH4qPJX/m5YN92ZCuIpocFUOsr9+q1NrMDUlmVrLzTA7MTIn1RVCggDQMwL7gdkQDnTz9ROvCWQnKFYlo2PRB7E/PhSNgsBn6FvpXJLNjv640eaNI9h82n4IMzJWEjMyUJNGXxRL1gvyUGrFJ+7DavJVTbnN1zq1SBZRTgVsvCHWGR3fMjFa3Nw9YQpThR6W8LYCXclSOX+RnKmeThxaKuYjm3up2jBJFWdqxswqWQQl0J/HLuD2KGfvz3D0hgKy7ytIhOtKzJAJklR4N/GSqjYvK80CfYBdddhxAsjMp/nB0Fud5zeM6gCPzp9YxK/KLo9C3UyGV7BCci915y49g8+9gicBYlHULdD5KG4VlsFRyuVGXEI6Z7nkA6JOAaiNsWjLcPFKF9CjAn0idfrvx//sBxoSz36WDZOTxD7tWHAE0fdxvJsMOzSdEgdl/8uIDoukdw5UrG4j2UsF/wWfUf8harerktWpaYj69PzDjdc1Pn6xOziunlEzeYLC44uElSvFfAPi/ABYNk8J3SxVEXVyh/lfvqzbJfk1cQk0aT4z/j2Lq1Z50p89k/fQq1louOkAqLPxcxI=
