version: "3"

services:
  # greeter-grpc is used as network alias and must match addressDB value in pkg handlers
  gocloud-grpc:
    image: marktward/gocloud:latest
    command: gocloud grpc serve
    expose:
      - 8000

  restapi:
    image: marktward/gocloud:latest
    ports:
      - 8010:8010
    command: gocloud restapi start
