apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocloud-grpc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gocloud
        tier: backend
        component: grpc
    spec:
      containers:
      - name: gocloud-be
        imagePullPolicy: Always
        image: marktward/gocloud:latest
        ports:
          - name: gocloud-be
            containerPort: 8000
        command: ["gocloud", "grpc", "serve"]
