apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocloud-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gocloud
        tier: frontend
        component: web
    spec:
      containers:
      - name: gocloud-fe
        imagePullPolicy: Always
        image: marktward/gocloud:latest
        ports:
        - containerPort: 8010
          name: gocloud-fe
        command: ["gocloud", "restapi", "start"]
