apiVersion: v1
kind: Service
metadata:
  # TODO: name must match addressDB in restapi/endpoints; push into chart
  name: gocloud-grpc
spec:
  selector:
    app: greeter
    tier: backend
    component: grpc
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
