apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # name: {{ .Values.service.gocloudGrpc.name }}
  # name: {{ template "fullname" . }}-grpc
  name: {{ .Release.Name }}-grpc
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    component: {{.Release.Name}}-{{ .Values.service.gocloudGrpc.labels.component }}
spec:
  replicas: {{ .Values.service.gocloudGrpc.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.gocloudGrpc.labels.app }}
        tier: {{ .Values.service.gocloudGrpc.labels.tier }}
        component: {{.Release.Name}}-{{ .Values.service.gocloudGrpc.labels.component }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
      - name: gocloud-be
        # BUG: helm converts all numeric commit tag to floating point! hacky workaround by forcing string from https://github.com/kubernetes/helm/issues/1707
        # image: {{ .Values.service.gocloudGrpc.image.repository}}:{{.Values.service.gocloudGrpc.image.tag}}
        image: {{ .Values.service.gocloudGrpc.image.repository}}:{{.Values.service.gocloudGrpc.image.tag | replace ":" "" }}
        imagePullPolicy: {{ .Values.service.gocloudGrpc.image.pullPolicy}}
        ports:
        - containerPort: {{ .Values.service.gocloudGrpc.ports.containerPort }}
          name: {{ .Values.service.gocloudGrpc.ports.name }}
        command: {{ .Values.service.gocloudGrpc.command }}
